version = 1

[[annotations]]
path = ["*.png"]
SPDX-FileCopyrightText = ["Ghommie", "EmoGarbage404"]
SPDX-License-Identifier = "CC-BY-SA-3.0"
SPDX-FileAttributionText = "https://github.com/tgstation/tgstation/commit/9c7d509354ee030300f63c701da63c17928c3b3b"
